const char box_httpd_lua[] =
"-- box.httpd\n"
"\n"
"(function(box)\n"
"    print(\"Plugin box.httpd init...\")\n"
"\n"
"    local ffi = require(\"ffi\")\n"
"\n"
"    local function errorf(fmt, ...)\n"
"        error(string.format(fmt, ...))\n"
"    end\n"
"    local function printf(fmt, ...)\n"
"        print(string.format(fmt, ...))\n"
"    end\n"
"\n"
"    local function process_client(self, s)\n"
"        box.fiber.wrap(function()\n"
"            printf('box.httpd: accepted connection %s', s)\n"
"            s:send(\"aaaaaaaaaaaaa\\n\")\n"
"            s:send(\"aaaaaaaaaaaaa\\n\")\n"
"            s:shutdown( box.socket.SHUT_RDWR )\n"
"            s:close()\n"
"        end)\n"
"    end\n"
"\n"
"\n"
"    local function httpd_start(self)\n"
"        if type(self) ~= 'table' then\n"
"            error(\"box.httpd: usage: httpd:start()\")\n"
"        end\n"
"        local s = box.socket.tcp()\n"
"        if s == nil then\n"
"            error(\"Can't create new tcp socket\")\n"
"        end\n"
"\n"
"\n"
"        local res = { s:bind(self.host, self.port) }\n"
"        if res[1] == 'error' then\n"
"            errorf(\"Can't bind socket: %s\", res[3])\n"
"        end\n"
"\n"
"        res = { s:listen() }\n"
"        if res[1] == 'error' then\n"
"            errorf(\"Can't listen socket: %s\", res[3])\n"
"        end\n"
"\n"
"        rawset(self, 'is_run', true)\n"
"        rawset(self, 's', s)\n"
"\n"
"        box.fiber.wrap(function()\n"
"            printf('box.httpd: started at host=%s, port=%s',\n"
"                self.host, self.port)\n"
"            while self.is_run do\n"
"                local cs, status, errstr = s:accept(.5)\n"
"                if cs == 'error' then\n"
"                    printf(\"Can't accept socket: %s\", cs, errstr)\n"
"                    break\n"
"                elseif cs ~= 'timeout' then\n"
"                    process_client(self, cs)\n"
"                    cs = nil\n"
"                end\n"
"            end\n"
"            self.s:close()\n"
"            rawset(self, 's', nil)\n"
"            rawset(self, 'is_run', false)\n"
"        end)\n"
"\n"
"    end\n"
"\n"
"\n"
"    box.httpd = {\n"
"        new = function(host, port, options)\n"
"            local self = {\n"
"                host    = host,\n"
"                port    = port,\n"
"                is_run  = false,\n"
"                stop    = function() error(\"http server is not started\") end,\n"
"                start   = httpd_start,\n"
"                options = options\n"
"            }\n"
"\n"
"            return self\n"
"        end\n"
"    }\n"
"\n"
"\n"
"end)(box)\n"
"\n"
""
;
